import os
import subprocess
import shutil

# --- Configuration ---
# Folders that store intermediate results
DIRS_TO_CLEAN = [
    "txtfiles",
    "barcodes",
    "results_kernel"
]

# Specific generated files in the data directory to remove
DATA_FILES_TO_CLEAN = [
    "data/selected_files.txt",
    "data/dist_raw_euclidean.npy",
    "data/mds_raw_images.png",
    "data/tsne_raw_images.png",
    
    "data/dist_H0_bottleneck.npy",
    "data/H0_bottleneck_file_order.npy",
    "data/dist_H0_wasserstein.npy",
    "data/H0_wasserstein_file_order.npy",
    
    "data/dist_H1_bottleneck.npy",
    "data/H1_bottleneck_file_order.npy",
    "data/dist_H1_wasserstein.npy",
    "data/H1_wasserstein_file_order.npy",
    
    "data/mds_H0_bottleneck.png",
    "data/mds_H0_wasserstein.png",
    "data/mds_H1_bottleneck.png",
    "data/mds_H1_wasserstein.png",
]

# The t-SNE files generated by the general tsne script
TSNE_PROFIT = [
    "data/tsne_H0_bottleneck.png",
    "data/tsne_H0_wasserstein.png",
    "data/tsne_H1_bottleneck.png",
    "data/tsne_H1_wasserstein.png",
]
DATA_FILES_TO_CLEAN.extend(TSNE_PROFIT)


# The ordered list of scripts to run based on the report
PIPELINE_SCRIPTS = [
    # 1. Data Prep
    "make_manifest.py",
    
    # 2. Boundary Extraction
    "extract_all_boundaries.py",
    
    # 3. Barcode Computation (with diagonal normalization!)
    "compute_all_barcodes.py",
    
    # (Distance Computation removed from this list, run separately below)
    
    # 5. Embeddings / Visualize
    "raw_image_baseline.py",
    # (MDS Computation removed from this list, run separately below)
]

def clean_old_results():
    print("=== Cleaning Up Old Results ===")
    for d in DIRS_TO_CLEAN:
        if os.path.exists(d):
            print(f"Removing directory: {d}")
            shutil.rmtree(d)
        os.makedirs(d, exist_ok=True)
        print(f"Created empty directory: {d}")
        
    for f in DATA_FILES_TO_CLEAN:
        if os.path.exists(f):
            print(f"Removing file: {f}")
            os.remove(f)
    print("Cleanup complete.\n")

def run_script(script_name, *args):
    print(f"\n========================================")
    print(f"Running Step: {script_name} {' '.join(args)}")
    print(f"========================================")
    
    cmd = ["python", script_name] + list(args)
    result = subprocess.run(cmd)
    
    if result.returncode != 0:
        print(f"\n[ERROR] Pipeline stopped. {script_name} failed with return code {result.returncode}.")
        exit(result.returncode)
        
    print(f"[SUCCESS] Finished {script_name}\n")

if __name__ == "__main__":
    clean_old_results()
    
    for script in PIPELINE_SCRIPTS:
        run_script(script)
        
    print("\n========================================")
    print("Running Distance Computations")
    print("========================================")
    run_script("compute_H.py", "--mode", "h0b")
    run_script("compute_H.py", "--mode", "h0w")
    run_script("compute_H.py", "--mode", "h1b")
    run_script("compute_H.py", "--mode", "h1w")
        
    # Run t-SNE for the 4 distances using the custom flag format
    print("\n========================================")
    print("Running t-SNE Dimensionality Reduction")
    print("========================================")
    run_script("tsne_from_distance.py", "--mode", "h0b")
    run_script("tsne_from_distance.py", "--mode", "h0w")
    run_script("tsne_from_distance.py", "--mode", "h1b")
    run_script("tsne_from_distance.py", "--mode", "h1w")

    print("\n========================================")
    print("Running MDS Dimensionality Reduction")
    print("========================================")
    run_script("mds_H.py", "--mode", "h0b")
    run_script("mds_H.py", "--mode", "h0w")
    run_script("mds_H.py", "--mode", "h1b")
    run_script("mds_H.py", "--mode", "h1w")

    # 6. ML / Modeling
    print("\n========================================")
    print("Running Machine Learning Models (8-class and 4-class)")
    print("========================================")
    
    run_script("svm_persistence_images.py", "--mode", "8class")
    run_script("svm_persistence_images.py", "--mode", "4class")
    
    run_script("kernel_svm_persistence_scale_space.py", "--mode", "8class")
    run_script("kernel_svm_persistence_scale_space.py", "--mode", "4class")
    
    run_script("kernel_rep.py")

    print("\n========================================")
    print("PIPELINE COMPLETED SUCCESSFULLY!")
    print("========================================")
